python-fuse (2:1.0.0-1) unstable; urgency=medium

  This release contains a breaking change for Python 3, as it now uses
  bytes objects to read and write data; it's worth it however since it
  fixes a serious usability bug that arbitrarily limited file content
  to valid UTF-8 data.

 -- Sebastien Delafond <seb@debian.org>  Fri, 19 Jul 2019 06:58:10 +0200



